#!/bin/sh

## Open Applications
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/bin/eww"

if [[ "$1" == "--ms" ]]; then
	${EWW} close-all && rm -rf "$FILE" && microsoft-edge-stable &

elif [[ "$1" == "--tg" ]]; then
	${EWW} close-all && rm -rf "$FILE" && telegram-desktop &

elif [[ "$1" == "--dc" ]]; then
	${EWW} close-all && rm -rf "$FILE" && discord &

elif [[ "$1" == "--tr" ]]; then
	${EWW} close-all && rm -rf "$FILE" && alacritty --working-directory ~ &

elif [[ "$1" == "--sp" ]]; then
	${EWW} close-all && rm -rf "$FILE" && spotify ~ &

elif [[ "$1" == "--st" ]]; then
	${EWW} close-all && rm -rf "$FILE" && steam-native &

elif [[ "$1" == "--cd" ]]; then
	${EWW} close-all && rm -rf "$FILE" && code &

elif [[ "$1" == "--gp" ]]; then
	${EWW} close-all && rm -rf "$FILE" && gimp &

elif [[ "$1" == "--vm" ]]; then
	${EWW} close-all && rm -rf "$FILE" && virt-manager &

fi
