#!/bin/sh

## Open links in firefox
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/bin/eww"
cmd="xdg-open"

if [[ "$1" == "--mail" ]]; then
	${EWW} close-all && rm -rf "$FILE" && ${cmd} "https://mail.google.com"

elif [[ "$1" == "--gh" ]]; then
	${EWW} close-all && rm -rf "$FILE" && ${cmd} "https://github.com"

elif [[ "$1" == "--rd" ]]; then
	${EWW} close-all && rm -rf "$FILE" && ${cmd} "https://reddit.com"

elif [[ "$1" == "--lor" ]]; then
	${EWW} close-all && rm -rf "$FILE" && ${cmd} "https://linux.org.ru"

elif [[ "$1" == "--yt" ]]; then
	${EWW} close-all && rm -rf "$FILE" && ${cmd} "https://youtube.com"
	
elif [[ "$1" == "--tw" ]]; then
	${EWW} close-all && rm -rf "$FILE" && ${cmd} "https://twitch.tv"	

fi
