#!/bin/bash
killall dunst
dunst -verbosity mesg -config ~/.config/dunst/dunstrc &

notify-send -u critical "Test message: critical test 1"
notify-send -u normal "Test message: normal test 2"
notify-send -u low "Test message: low test 3"
